    @Test
    public final void testScope() throws Exception {
        try (Workbook wb = _testDataProvider.createWorkbook()) {
            wb.createSheet();
            wb.createSheet();

            wb.createName().setNameName("aaa");
            Exception e = assertThrows(Exception.class, () -> wb.createName().setNameName("aaa"));
            assertEquals("The workbook already contains this name: aaa", e.getMessage());

            Name name1 = wb.createName();
            name1.setSheetIndex(0);
            name1.setNameName("aaa");

            e = assertThrows(Exception.class, () -> {
                Name name2 = wb.createName();
                name2.setSheetIndex(0);
                name2.setNameName("aaa");
            });
            assertEquals("The sheet already contains this name: aaa", e.getMessage());

            name1 = wb.createName();
            name1.setSheetIndex(1);
            name1.setNameName("aaa");

            e = assertThrows(Exception.class, () -> {
                Name name2 = wb.createName();
                name2.setSheetIndex(1);
                name2.setNameName("aaa");
            });
            assertEquals("The sheet already contains this name: aaa", e.getMessage());

            assertEquals(3, wb.getNames("aaa").size());
        }
    }

