    @Test
    public void testRewritableFile() throws Exception {
        File temp = TempFile.createTempFile("TestDataSource", ".test");
        try {
            writeDataToFile(temp);

            ;
            try (FileBackedDataSource ds = new FileBackedDataSource(temp, true)) {
                ByteBuffer buf = ds.read(0, 10);
                assertNotNull(buf);
                buf = ds.read(8, 0x400);
                assertNotNull(buf);
            }

            // try a second time
            ;
            try (FileBackedDataSource ds = new FileBackedDataSource(temp, true)) {
                ByteBuffer buf = ds.read(0, 10);
                assertNotNull(buf);
                buf = ds.read(8, 0x400);
                assertNotNull(buf);
            }

            writeDataToFile(temp);
        } finally {
            assertTrue(temp.exists());
            assertTrue(temp.delete());
        }
    }

