    @Test
    void testFileWritable() throws Exception {
        File temp = TempFile.createTempFile("TestDataSource", ".test");
        try {
            writeDataToFile(temp);

            try (FileBackedDataSource ds = new FileBackedDataSource(temp, false))  {
                checkDataSource(ds, true);
            }

            // try a second time
            try (FileBackedDataSource ds = new FileBackedDataSource(temp, false)) {
                checkDataSource(ds, true);
            }

            writeDataToFile(temp);
        } finally {
            assertTrue(temp.exists());
            assertTrue(temp.delete(), "Could not delete file " + temp);
        }
    }

